services:
  allocation:
    image: divyadocker22/allocationimage:latest
    container_name: allocation-ms
    ports:
      - "8081:8081"
    networks:
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  security:
    image: divyadocker22/allocationsecurityimage:latest
    container_name: allocation-security-ms
    ports:
      - "8091:8091"
    networks:
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
      image: bitnami/kafka:latest
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

networks:
  microservice-network:
    driver: bridge

